#!/usr/bin/env php
<?php

// get environment constants or set default
if (!defined('UMASK')) {
    define('UMASK', 0002);
}

set_time_limit(0);

require_once __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
define('SILEX_ENV', $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev'));
define('SILEX_DEBUG', !$input->hasParameterOption(array('--no-debug')));

/**
 * @var \Silex\Application Silex application
 */
$app = require_once __DIR__.'/bootstrap_app.php';
$app->boot();

/**
 * @var \Symfony\Component\Console\Application Console application
 */
$console = require_once __DIR__.'/bootstrap_console.php';
$console->run();